site_name: PHP on Kalabox Documentation
theme: readthedocs
repo_url: https://github.com/kalabox/kalabox-app-php
include_search: true
markdown_extensions:
  - markdown.extensions.toc
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.nl2br
pages:
  - 'Homepage': 'index.md'
  - 'For Users':
    - 'Installation': 'users/install.md'
    - 'Using the CLI': 'users/cli.md'
    - 'Using the GUI': 'users/gui.md'
    - 'Services': 'users/services.md'
    - 'Dev Tools': 'users/tooling.md'
    - 'Configuration': 'users/config.md'
  - 'For Developers': 'developers.md'
  - 'Troubleshooting': 'troubleshooting.md'
